{{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: dextercai/palword_server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8211
          protocol: UDP
        - containerPort: 25575
        volumeMounts:
        - name: savedGameVol
          mountPath: /home/steam/Steam/steamapps/common/PalServer/Pal/Saved
          mountPropagation: HostToContainer
      volumes:
        - name: savedGameVol
          hostPath:
            path: {{.Values.gameSavedDir}}
            type: DirectoryOrCreate
