apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.loadBalancePort }}
    targetPort: 8211
    protocol: UDP
    name: game-port
  {{- if .Values.enableRcon -}}
  - port: {{ .Values.loadBalanceRconPort }}
    targetPort: 25575
    protocol: TCP
    name: rcon-port
  {{- end -}}
  selector:
    app: {{ $fullname }}
